clean up gh action settings

diff --git a/.github/workflows/publish-docs.yml b/.github/workflows/publish-docs.yml
--- a/.github/workflows/publish-docs.yml
+++ b/.github/workflows/publish-docs.yml
@@ -14,15 +14,9 @@ jobs:
         with:
           flutter-version: '3.32.0'
       - run: flutter pub get
-      # - name: Create proper dartdoc config
-      #   run: |
-      #     echo 'dartdoc:
-      #       includeExternal: [README.md]
-      #       ' > dartdoc_options.yaml
-      #       cat dartdoc_options.yaml
       - name: Verify README.md files exist
         run: |
-          ls -la README.md
+          ls -la README.md || echo "README is exist"
       - name: Clean doc/api and run dartdoc
         run: | 
           rm -rf doc/api/
@@ -36,12 +30,11 @@ jobs:
           ls -la doc/api/ || echo "doc/api directory is empty or not found."
       - name: Prepare public folder
         run: |
-          mkdir -p docs
           mv doc/api/* . || echo "No files to move, proceeding..."
       - name: Create .nojekyll file
         run: touch .nojekyll # Extra safety to disable Jekyll
       - name: Debug publish directory
-        run: ls -R ./docs || echo "/docs directory is empty or not found"        
+        run: ls -R ./ || echo "Directory is empty or not found"        
       - name: Deploy o GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
